#load zap
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

setopt histignorealldups sharehistory

# Load and initialise completion system
autoload -Uz compinit
compinit

# load local configs with zap
plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/exports.zsh"
plug "$HOME/.config/zsh/completions.zsh"

# load plugins with zap
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "esc/conda-zsh-completion"
plug "zap-zsh/vim"
plug "Freed-Wu/fzf-tab-source" 
plug "Aloxaf/fzf-tab" 
plug "MichaelAquilina/zsh-you-should-use"
plug "chivalryq/git-alias"


eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
